# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end

usernames = [
  'admin1', 'user1', 'user2', 'user3',
  'user4', 'user5', 'user6', 'user7',
  'user8', 'user9', 'user10', 'user11',
  'user12', 'user13', 'user14', 'guest'
]

puts "Seeding begins ... "

usernames.each do |username|
  User.create!(
    username: username,
    firstname: Faker::Name.first_name,
    lastname: Faker::Name.last_name,
    password: "123456",
    password_confirmation: "123456",
    description: "Generated by faker, " + Faker::Lorem.sentence(word_count: 5),
    email: Faker::Internet.email(name: username)
  )
  puts username
end

puts "Seeding ended."
